name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '12.22.9'  # Specify Node.js version 12.x
        # You can also specify the exact version: '12.22.9'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test
